name: UniversalScheduler
version: ${project.version}
main: com.github.Anon8281.universalScheduler.UniversalScheduler
folia-supported: true
api-version: 1.19
authors: [ Sevastjan, Anon8281, Several]
website: politcubes.com
