name: Maven Compile
on: [ push, pull_request ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up OpenJDK 18
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '18'
      - name: Compile with Maven
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: mvn -B package --file pom.xml
      - name: Upload Artifact
        uses: actions/upload-artifact@v2-preview
        with:
          name: build
          path: target/*.jar